apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This ensures everything listed below is deployed into the namespace 
# created by your namespace.yaml
namespace: microservices-prod

resources:
  - namespace.yaml
  - pgsql-service.yaml
  - pgsql-statefulset.yaml 
