apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: microservices-prod
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: api-service
        image: gopidevops01/api-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "pgsql-service"
        # Using the same keys as your identity-platform service
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-db-secret
              key: POSTGRES_DB
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-db-secret
              key: POSTGRES_PASSWORD
        # Prisma-specific requirement
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-db-secret
              key: DATABASE_URL
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
