apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: microservices-prod
spec:
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: sealed-secrets
      containers:
      - name: migrate
        image: gopidevops01/api-service:latest
        command: ["npx", "prisma", "db", "push", "--schema=./node_modules/.prisma/client/schema.prisma"]
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres-db-secret
                key: DATABASE_URL
