---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-db-secret
  namespace: microservices-prod
spec:
  encryptedData:
    POSTGRES_DB: AgCRgoUCiPOpeqOAi0p7SYrFZEVdKydWshu7a1U7UUO8sY+vt3hX6d54Lgffi+qlwl2XXGateJXnfDhEFZL5e4o7Y8G0Od50Llk6ZujaD9zHU1xzyUSG/33ENTbkz8U4USUkeC9kRfCacuDHfiVIcsQOQ+zPHWIzFEImMG/hdPrb5jMLQ8wtni3Kfx/fE80AI/ifWs9UScOP2FNYfiT52NGm14vfXS87ZhW7mi4TOhjPrQ+yZb2lFBlBs8fdva53Imf97NZt0vh60xKbRiE8ZB/NLpVhaDsmAY+BlGy1GDTpxfgrSJ9RTNG67nJcextP6DL8VVAosAXkl8f1XtRKwCpjdu/7HV3o7fENA2k2FAc6cKJVL55/hgI4OfLskJXCpg0bUlRnecb9nS7HQZbPExpiZGXs7Alv9SKK8L9Dc4T2lnDdhmkDc7SGz2fPXDBDHib49xU8uyQHhZ8ei1id3juDDPeR5aQIJpyK07/W6pw6ddpaSBS1a8smlZc9TdRgQLz7OCqsYeDB3w1lPvuTsdDlaxZfK1uA/mTYTuzc3ffSzyYIYJaddBS9JOvMe4yJBOlEHR/8lvKHbSdDfWLoaUQrwgo7oED3tiL3RI3HZI4yqxhDtFeCeQyKLt5ZQ+wmHDBKLDanCvu1J9EG6HDsRgTFbroUBSm0ymZIFiNIulMV+0wWl67PXJoid4G+cVWC47fDhRR6Qu9Cu+Y9
    POSTGRES_PASSWORD: AgAceKkxHe9Kr1X2Z7HeFjhAO2tW9xj2U1ls7+4rGY/+LacUGN+Cq3Lf1JA8DC9z2p565yLSOe1h9A5KOgPiNtyvJkHQGjGIQKQcM+qw0ccNDTtKvxHpJPbcY/nDNtovtp1KtM+InooFsmasj0IfnWzJKJpJVArOvudVDTpAfC9gX413wE9umBzUY3kFlNpgiBBh44wcttxlyjLydyb/WzPte0WaioxWnquEOsGMmIMUR4HMbjwnB8AOjpDtzLmIOO4nF5Eg+JcPRrLhCbA5cTV843kuM+aboghEWDpYqt2InSVZ3qMRAPRXkYuVEvqLE1klUWUQ/DfOiXfE8gDcUBLtyVFs60ZsOkQ8f2O0mHGSCE4VcePCjPMurnuq5UfTwIRXzguve17aT6isozNhkZmfNZaAdDOu5VvRjW3iMD6MB0Us4RBimwOJmms5Lbk8fbWMDAciqGXaKQLWwEV5HYsuD2bhdfiGIm7L8mKJ/tlyxFpWksyeAW+Gjn/4DXrA3QRjkxNB9qT/l+LjIA55RsPnL71kGVNE0Jsq9XLGb+Wv4Sg7mB5UFWh+cydnNwz6HebtRwoqK66OizHbAfL2iIa579HPvQVT0XjCJqczObfDuCch+vRX6kN1/gIIfakjwZ/UERMaej31FmTO+VNqhQlzl+iv5LDbn+6JG4XCBnd8ALT9ZURnmbRpHn4NluZeJMokDniGBn9A5/2oUA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-db-secret
      namespace: microservices-prod
    type: Opaque
