apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ccoe
resources:
  - namespace.yaml
  - deployment.yaml
  - sealed-secret.yaml
  - repo.yaml
  - monitoring-stack.yaml
  - grafana-ingress.yaml
