apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: ccoe
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: ccoe
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.2.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: ccoe
  values:
    grafana:
      enabled: true
      adminPassword: "admin"
      service:
        type: LoadBalancer
      grafana.ini:
        smtp:
          enabled: true
          host: smtp.gmail.com:587
          user: gopidevops2025@gmail.com
          password: "jlumzcumvkyrhelv"
          skip_verify: true
          from_address: grafana-alerts@capstone.local
          from_name: Grafana Capstone Alerts
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
