apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: ccoe
spec:
  interval: 5m
  chart:
    spec:
      chart: k8s-monitoring
      version: "4.3.0"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: ccoe
  values:
    cluster:
      name: capstone-nexus
    destinations:
      grafana-cloud-metrics:
        type: prometheus
        url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push
        auth:
          type: basic
          username: "3381078"
          password:
            secret:
              name: grafana-token
              key: metrics-token
      grafana-cloud-logs:
        type: loki
        url: https://logs-prod-028.grafana.net/loki/api/v1/push
        auth:
          type: basic
          username: "1686214"
          password:
            secret:
              name: grafana-token
              key: logs-token
    clusterMetrics:
      enabled: true
      collector: alloy-metrics
    hostMetrics:
      enabled: true
      collector: alloy-metrics
      linuxHosts:
        enabled: true
      windowsHosts:
        enabled: true
      energyMetrics:
        enabled: true
    costMetrics:
      enabled: false
    clusterEvents:
      enabled: true
      collector: alloy-singleton
    podLogsViaLoki:
      enabled: true
      collector: alloy-logs
    collectors:
      alloy-metrics:
        presets: [clustered, statefulset]
        remoteConfig:
          enabled: true
          url: https://fleet-management-prod-018.grafana.net
          auth:
            type: basic
            username: "1728427"
            passwordKey: "alloy-token"
          secret:
            create: false
            name: grafana-token
      alloy-singleton:
        presets: [singleton]
        remoteConfig:
          enabled: true
          url: https://fleet-management-prod-018.grafana.net
          auth:
            type: basic
            username: "1728427"
            passwordKey: "alloy-token"
          secret:
            create: false
            name: grafana-token
      alloy-logs:
        presets: [filesystem-log-reader, daemonset]
        remoteConfig:
          enabled: true
          url: https://fleet-management-prod-018.grafana.net
          auth:
            type: basic
            username: "1728427"
            passwordKey: "alloy-token"
          secret:
            create: false
            name: grafana-token
    telemetryServices:
      kube-state-metrics:
        deploy: true
      node-exporter:
        deploy: true
      windows-exporter:
        deploy: true
      kepler:
        deploy: true
      opencost:
        deploy: false
