---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-token
  namespace: ccoe
spec:
  encryptedData:
    token: AgCUvBqBdxi6ia7PVGRK/TwLajP108vtKLm1Zi3tZBF74SQ0G7Mp5BICEzZAHRgO8iMQ2Pf0fSzvbhFqO8tzPEsKdDom1MVUHxbXaGS/b19YMBVxmayWwsrLGOkTasasW996tlrz2Afj3NVP1eRhpfXKZn+ScN3i2H6dfgL5xHP0+VXVIHFScDXTrfNi1XT7xesyGFu0H/jz+q8U76Zdiawp72/Cn38tLATXkrjcxu2/GMmlevyhUPekuSYjaTkKhBJQkT/uiaro5FYPXGIw1Vt3ow9DjUdoaYCfrVgVShpksGDNh2ldIOYr89ZLhLoEQE7FuXt9LOzwZVYzcR1y/S6DZmFhhpdmKG8Snqk9MHuyWoFbIqsKBbJy1Q+6nQ+vyAoIKJ1oAPqynOaGGMsu2ud5WDDWBaERo1skiZOZIjQTLOB7FpF/lfhugtmWmqPuwTe9lmFaCoeboBcx6MJP3zT70zyrgOS7Gg9VKO2qj68nsUxKHUEVPuekeXrCl9KcUAOkRH8E52gFWzzcU5eC2IrygkMsZrVZvN2cz/k8M+Dlcg2cdjKnluZXw28bc9PhPGUflNUNXdESub822nmsYGA3o7EZSaTd/b/yWRihLsdmgq98s4I/dHtvlCBRWcEBOMNEQJm33cM7FlKAnUgv1DisOrqrXHSENPLRSBdn87ejKJTdNULDoPPAls+g8XZNojOUosmVeCNx5QIgDYV0xyj3HEYn6JfqMoZ6F9X1jOEYp7iX0tW54H7MsvzHN+6LlY5TwWpoGKB0dlDh/69GJ9GrA5NhyM51WKQ2EyEh8qwlY/tHhYepzSq/rBSOc7umrgnsUpCj6W3V9WUaNrjppKME21RInvJ9H9qMETQ8QXclFzIWDBZ1FxtsR1TzMVDyVmVE9R3veG2eIeUpgPPl8EUWdE/Wm61aMVJiUjbHPXgllmDByCLcpsUmQU6iiBAHJMZ8ciT9SpFQezkWTIk=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-token
      namespace: ccoe
